### ISSUE TITLE
not support php7

### ISSUE THREAD

**Issue by yherus** [maplechori/php_stata#2]
Dear Montero,

I am trying to compile on CentOS 7 with php version 7 and got an error :

[root@localhost php_stata]# ls
acinclude.m4    config.guess  config.m4      configure     libtool    Makefile.fragments  mkinstalldirs  stata.c      statawrite.c
aclocal.m4      config.h      config.nice    configure.in  LICENSE    Makefile.global     modules        stata.h      swap_bytes.h
autom4te.cache  config.h.in   config.status  include       ltmain.sh  Makefile.objects    README.md      stataread.c
build           config.log    config.sub     install-sh    Makefile   missing             run-tests.php  stataread.h
[root@localhost php_stata]# make
/bin/sh /home/yhs/php_stata/libtool --mode=compile cc  -I. -I/home/yhs/php_stata -DPHP_ATOM_INC -I/home/yhs/php_stata/include -I/home/yhs/php_stata/main -I/home/yhs/php_stata -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/yhs/php_stata/stata.c -o stata.lo
libtool: compile:  cc -I. -I/home/yhs/php_stata -DPHP_ATOM_INC -I/home/yhs/php_stata/include -I/home/yhs/php_stata/main -I/home/yhs/php_stata -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/yhs/php_stata/stata.c  -fPIC -DPIC -o .libs/stata.o
/home/yhs/php_stata/stata.c: In function 'zif_stata_nvariables':
/home/yhs/php_stata/stata.c:127:29: error: expected expression before 'struct'
   ZEND_FETCH_RESOURCE (dta, struct StataDataFile _, &stataData, -1,
                             ^
/home/yhs/php_stata/stata.c: In function 'zif_stata_close':
/home/yhs/php_stata/stata.c:155:29: error: expected expression before 'struct'
   ZEND_FETCH_RESOURCE (dta, struct StataDataFile *, &stataData, -1,
                             ^
/home/yhs/php_stata/stata.c: In function 'zif_stata_observations':
/home/yhs/php_stata/stata.c:180:29: error: expected expression before 'struct'
   ZEND_FETCH_RESOURCE (dta, struct StataDataFile *, &stataData, -1,
                             ^
/home/yhs/php_stata/stata.c: In function 'zif_stata_variables':
/home/yhs/php_stata/stata.c:210:29: error: expected expression before 'struct'
   ZEND_FETCH_RESOURCE (dta, struct StataDataFile *, &stataData, -1,
                             ^
/home/yhs/php_stata/stata.c:230:70: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
       add_assoc_string (innerarray[count], "vlabels", stv->vlabels, 1);
                                                                      ^
/home/yhs/php_stata/stata.c:230:7: error: 'add_assoc_string' undeclared (first use in this function)
       add_assoc_string (innerarray[count], "vlabels", stv->vlabels, 1);
       ^
/home/yhs/php_stata/stata.c:230:7: note: each undeclared identifier is reported only once for each function it appears in
/home/yhs/php_stata/stata.c:231:70: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
       add_assoc_string (innerarray[count], "dlabels", stv->dlabels, 1);
                                                                      ^
/home/yhs/php_stata/stata.c:232:64: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
       add_assoc_string (innerarray[count], "vfmt", stv->vfmt, 1);
                                                                ^
/home/yhs/php_stata/stata.c: In function 'zif_stata_labels':
/home/yhs/php_stata/stata.c:257:29: error: expected expression before 'struct'
   ZEND_FETCH_RESOURCE (dta, struct StataDataFile *, &stataData, -1,
                             ^
/home/yhs/php_stata/stata.c:289:57: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
    add_assoc_string (innerarray[0], buff, stl->string, 1);
                                                         ^
/home/yhs/php_stata/stata.c:289:4: error: 'add_assoc_string' undeclared (first use in this function)
    add_assoc_string (innerarray[0], buff, stl->string, 1);
    ^
/home/yhs/php_stata/stata.c:296:65: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
        add_assoc_string (innerarray[count], buff, stl->string, 1);
                                                                 ^
/home/yhs/php_stata/stata.c:302:62: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
     add_assoc_string (innerarray[count], buff, stl->string, 1);
                                                              ^
/home/yhs/php_stata/stata.c:313:65: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
        add_assoc_string (innerarray[count], buff, stl->string, 1);
                                                                 ^
/home/yhs/php_stata/stata.c: In function 'zif_stata_data':
/home/yhs/php_stata/stata.c:356:29: error: expected expression before 'struct'
   ZEND_FETCH_RESOURCE (dta, struct StataDataFile *, &stataData, -1, PHP_STATA_FILE_RES_NAME, le_stata_file);
                             ^
/home/yhs/php_stata/stata.c:401:79: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
        add_assoc_string (vararray[counterObs], stv->name, obd->value.string, 1);
                                                                               ^
/home/yhs/php_stata/stata.c:401:8: error: 'add_assoc_string' undeclared (first use in this function)
        add_assoc_string (vararray[counterObs], stv->name, obd->value.string, 1);
        ^
/home/yhs/php_stata/stata.c: In function 'zif_stata_write':
/home/yhs/php_stata/stata.c:431:5: warning: passing argument 2 of 'zend_hash_exists' from incompatible pointer type [enabled by default]
     if (zend_hash_exists(Z_ARRVAL_P(labels), "labels", sizeof("labels"))) {
     ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:159:34: note: expected 'struct zend_string *' but argument is of type 'char *'
 ZEND_API zend_bool ZEND_FASTCALL zend_hash_exists(const HashTable *ht, zend_string *key);
                                  ^
/home/yhs/php_stata/stata.c:431:5: error: too many arguments to function 'zend_hash_exists'
     if (zend_hash_exists(Z_ARRVAL_P(labels), "labels", sizeof("labels"))) {
     ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:159:34: note: declared here
 ZEND_API zend_bool ZEND_FASTCALL zend_hash_exists(const HashTable *ht, zend_string *key);
                                  ^
/home/yhs/php_stata/stata.c:435:11: warning: passing argument 2 of 'zend_hash_find' from incompatible pointer type [enabled by default]
           zend_hash_find(Z_ARRVAL_P(labels), "labels", sizeof("labels"), (void *_)&innerLabels);
           ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:154:30: note: expected 'struct zend_string _' but argument is of type 'char *'
 ZEND_API zval_ ZEND_FASTCALL zend_hash_find(const HashTable _ht, zend_string *key);
                              ^
/home/yhs/php_stata/stata.c:435:11: error: too many arguments to function 'zend_hash_find'
           zend_hash_find(Z_ARRVAL_P(labels), "labels", sizeof("labels"), (void *_)&innerLabels);
           ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:154:30: note: declared here
 ZEND_API zval\* ZEND_FASTCALL zend_hash_find(const HashTable _ht, zend_string *key);
                              ^
/home/yhs/php_stata/stata.c:437:11: warning: passing argument 1 of 'zend_hash_internal_pointer_reset_ex' makes pointer from integer without a cast [enabled by default]
           for (zend_hash_internal_pointer_reset_ex(Z_ARRVAL_PP(innerLabels), &position);
           ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:172:30: note: expected 'struct HashTable *' but argument is of type 'int'
 ZEND_API void  ZEND_FASTCALL zend_hash_internal_pointer_reset_ex(HashTable *ht, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:438:82: error: 'zend_value' has no member named 'ht'
                               zend_hash_get_current_data_ex((_innerLabels)->value.ht, (void**) &vlabels, &position) == SUCCESS;
                                                                                  ^
/home/yhs/php_stata/stata.c:438:31: warning: passing argument 2 of 'zend_hash_get_current_data_ex' from incompatible pointer type [enabled by default]
                               zend_hash_get_current_data_ex((*innerLabels)->value.ht, (void**) &vlabels, &position) == SUCCESS;
                               ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:171:30: note: expected 'HashPosition _' but argument is of type 'void *_'
 ZEND_API zval\* ZEND_FASTCALL zend_hash_get_current_data_ex(HashTable _ht, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:438:31: error: too many arguments to function 'zend_hash_get_current_data_ex'
                               zend_hash_get_current_data_ex((_innerLabels)->value.ht, (void*_) &vlabels, &position) == SUCCESS;
                               ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:171:30: note: declared here
 ZEND_API zval_ ZEND_FASTCALL zend_hash_get_current_data_ex(HashTable _ht, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:439:80: error: 'zend_value' has no member named 'ht'
                                 zend_hash_move_forward_ex((_innerLabels)->value.ht, &position)) {
                                                                                ^
/home/yhs/php_stata/stata.c:449:7: warning: passing argument 1 of 'zend_hash_get_current_key_ex' makes pointer from integer without a cast [enabled by default]
       key_type = zend_hash_get_current_key_ex(Z_ARRVAL_PP(vlabels), &key, &key_len, &index, 0, &position);
       ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:168:30: note: expected 'const struct HashTable _' but argument is of type 'int'
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string *_str_index, zend_ulong _num_index, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:449:7: warning: passing argument 2 of 'zend_hash_get_current_key_ex' from incompatible pointer type [enabled by default]
       key_type = zend_hash_get_current_key_ex(Z_ARRVAL_PP(vlabels), &key, &key_len, &index, 0, &position);
       ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:168:30: note: expected 'struct zend_string *_' but argument is of type 'char *_'
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string *_str_index, zend_ulong _num_index, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:449:7: warning: passing argument 3 of 'zend_hash_get_current_key_ex' from incompatible pointer type [enabled by default]
       key_type = zend_hash_get_current_key_ex(Z_ARRVAL_PP(vlabels), &key, &key_len, &index, 0, &position);
       ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:168:30: note: expected 'zend_ulong *' but argument is of type 'uint *'
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string *_str_index, zend_ulong _num_index, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:449:7: warning: passing argument 4 of 'zend_hash_get_current_key_ex' from incompatible pointer type [enabled by default]
       key_type = zend_hash_get_current_key_ex(Z_ARRVAL_PP(vlabels), &key, &key_len, &index, 0, &position);
       ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:168:30: note: expected 'HashPosition *' but argument is of type 'long int *'
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string *_str_index, zend_ulong _num_index, HashPosition *pos);
                              ^
/home/yhs/php_stata/stata.c:449:7: error: too many arguments to function 'zend_hash_get_current_key_ex'
       key_type = zend_hash_get_current_key_ex(Z_ARRVAL_PP(vlabels), &key, &key_len, &index, 0, &position);
       ^
In file included from /usr/include/php/Zend/zend.h:36:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/yhs/php_stata/stata.c:26:
/usr/include/php/Zend/zend_hash.h:168:30: note: declared here
 ZEND_API int   ZEND_FASTCALL zend_hash_get_current_key_ex(const HashTable *ht, zend_string *_str_index, zend_ulong _num_index, HashPosition *pos);
                              ^
make: *_\* [stata.lo] Error 1
[root@localhost php_stata]#

Would you help me to solve this problem, or tell me what I should do

**Comment by maplechori** [comment]
Unfortunately that module was written for php5. I haven't had time to upgrade it. The only way to fix it would be to adapt it to the programming model of php7.

Maybe you can spin a docker with php5 and run it through it.

**Comment by maplechori** [comment]
I am working on the PHP 7 version. Should be ready this week for testing.

**Comment by maplechori** [comment]
use the php7 branch
